-- Client360 — local development seed. NEVER run outside the local profile.
--
-- Lives outside db/migrations/ on purpose: seed data must not sit in V* files
-- that run in production (.claude/rules/db-migrations.md).
--
-- Scope of this file: teams and users only.
--
-- Clients and interactions are NOT seeded here. Their PII columns hold
-- AES-256-GCM ciphertext plus an HMAC lookup hash (SPEC.md §4.7), and pgcrypto
-- cannot produce GCM ciphertext the application would be able to decrypt.
-- Faking those columns would mean either embedding the data key in SQL or
-- inventing a plaintext key_version the production code would then have to
-- tolerate. Both are worse than the alternative: client and interaction seed
-- data is generated by a dev-profile ApplicationRunner in client-service, which
-- has the key. See db/README.md.
--
-- Re-runnable: every statement is ON CONFLICT DO NOTHING.

\set ON_ERROR_STOP on

BEGIN;

-- ------------------------------------------------------------------ teams
-- supervisor_id is set after users exist (circular FK).
INSERT INTO client.teams (id, name, code, timezone) VALUES
    ('7a000000-0000-4000-8000-000000000001', 'Retail Warsaw North', 'RWN', 'Europe/Warsaw'),
    ('7a000000-0000-4000-8000-000000000002', 'Retail Warsaw South', 'RWS', 'Europe/Warsaw')
ON CONFLICT (id) DO NOTHING;

-- ------------------------------------------------------------------ users
-- password_hash uses Spring Security's DelegatingPasswordEncoder {noop} prefix.
-- Local development only. The application must refuse to start with any {noop}
-- hash outside the `local` profile — that guard is part of the auth work in v2.
-- Every seeded user is forced through a password change on first login.
-- ck_users_deactivated_pair requires status='DEACTIVATED' and deactivated_at to
-- agree within the same row, so deactivated_at is set here rather than in a
-- follow-up UPDATE.
INSERT INTO client.users
    (id, employee_no, email, full_name, password_hash, status, primary_team_id,
     must_change_password, deactivated_at)
VALUES
    -- Team RWN
    ('3f000000-0000-4000-8000-000000000001', 'EMP-1001', 'o.wisniewska@bank.example',
     'Ola Wiśniewska',      '{noop}local-dev-only', 'ACTIVE', '7a000000-0000-4000-8000-000000000001', true, NULL),
    ('3f000000-0000-4000-8000-000000000002', 'EMP-1002', 'a.nowak@bank.example',
     'Adam Nowak',          '{noop}local-dev-only', 'ACTIVE', '7a000000-0000-4000-8000-000000000001', true, NULL),
    ('3f000000-0000-4000-8000-000000000003', 'EMP-1003', 'm.lewandowska@bank.example',
     'Marta Lewandowska',   '{noop}local-dev-only', 'ACTIVE', '7a000000-0000-4000-8000-000000000001', true, NULL),
    -- Team RWS
    ('3f000000-0000-4000-8000-000000000004', 'EMP-1004', 'p.kowalczyk@bank.example',
     'Piotr Kowalczyk',     '{noop}local-dev-only', 'ACTIVE', '7a000000-0000-4000-8000-000000000002', true, NULL),
    ('3f000000-0000-4000-8000-000000000005', 'EMP-1005', 'j.zielinski@bank.example',
     'Jan Zieliński',       '{noop}local-dev-only', 'ACTIVE', '7a000000-0000-4000-8000-000000000002', true, NULL),
    -- Cross-team roles (no primary team)
    ('3f000000-0000-4000-8000-000000000006', 'EMP-1006', 's.admin@bank.example',
     'Sofia Adamska',       '{noop}local-dev-only', 'ACTIVE', NULL, true, NULL),
    ('3f000000-0000-4000-8000-000000000007', 'EMP-1007', 'j.audyt@bank.example',
     'Jakub Audyt',         '{noop}local-dev-only', 'ACTIVE', NULL, true, NULL),
    ('3f000000-0000-4000-8000-000000000008', 'EMP-1008', 'e.zgodnosc@bank.example',
     'Ewa Zgodność',        '{noop}local-dev-only', 'ACTIVE', NULL, true, NULL),
    -- Deactivated, so RB-BR-07 / RB-EC-14 have something to test against.
    ('3f000000-0000-4000-8000-000000000009', 'EMP-1009', 'b.byly@bank.example',
     'Bartosz Były',        '{noop}local-dev-only', 'DEACTIVATED', NULL, false, now() - INTERVAL '30 days')
ON CONFLICT (id) DO NOTHING;

-- Close the circular reference.
UPDATE client.teams SET supervisor_id = '3f000000-0000-4000-8000-000000000001'
 WHERE id = '7a000000-0000-4000-8000-000000000001' AND supervisor_id IS NULL;
UPDATE client.teams SET supervisor_id = '3f000000-0000-4000-8000-000000000004'
 WHERE id = '7a000000-0000-4000-8000-000000000002' AND supervisor_id IS NULL;

COMMIT;

-- Intended role assignments, applied once user_roles exists in v2:
--   Ola Wiśniewska     SUPERVISOR (RWN)
--   Adam Nowak         MANAGER    (RWN)
--   Marta Lewandowska  MANAGER    (RWN)
--   Piotr Kowalczyk    SUPERVISOR (RWS)
--   Jan Zieliński      MANAGER    (RWS)
--   Sofia Adamska      ADMIN
--   Jakub Audyt        AUDITOR
--   Ewa Zgodność       COMPLIANCE

\echo 'Seed applied: 2 teams, 9 users (8 active, 1 deactivated).'
